package com.movienius.models;

import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * An entity User composed by three fields (id, email, name). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "movies")
public class Movie {
	// An autogenerated id (unique for each user in the db)
	@Id
	@Column
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@NotNull
	@Column
	private String title;

	@Column
	private String movie_url;

	@Column
	private String description;

	@Column
	private int year;

	@Column
	private String director;
	
	@Column(length=1024)
	private String actors;

	@Column
	private String poster_url;

	@Column
	private double rating;
	
	public Movie(){
		
	}
	
	public Movie(String title){
		this.title = title;
	}
	
	public Movie(String title, String movie_url){
		this.title = title;
		this.movie_url = movie_url;
	}

	public Movie(String title, String movie_url, String description, int year, String director, String actors,
			String poster_url, double rating) {
		this.title = title;
		this.movie_url = movie_url;
		this.description = description;
		this.year = year;
		this.director = director;
		this.actors = actors;
		this.poster_url = poster_url;
		this.rating = rating;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getMovie_url() {
		return this.movie_url;
	}

	public void setMovie_url(String movie_url) {
		this.movie_url = movie_url;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public String getActors() {
		return actors;
	}

	public void setActors(String actors) {
		this.actors = actors;
	}

	public String getPoster_url() {
		return this.poster_url;
	}

	public void setPoster_url(String poster_url) {
		this.poster_url = poster_url;
	}

	public double getRating() {
		return rating;
	}

	public void setRating(double rating) {
		this.rating = rating;
	}

	public long getId() {
		return id;
	}
}
